# Generated by Django 3.2.21 on 2023-12-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_username',
            new_name='user_profile',
        ),
    ]
