# Generated by Django 3.2.21 on 2024-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=35)),
                ('message', models.TextField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
