# Generated by Django 3.2.21 on 2024-01-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231022_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_info',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
